services:
  # Servicio Web para el Backend (Laravel con Docker)
  - type: web
    name: stocklimp-backend
    branch: APP-Android-IOS-Web
    env: docker
    region: frankfurt
    plan: free
    rootDir: back
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: StockLimp
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://stocklimp-backend.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-39007dc0-stocklimp.d.aivencloud.com
      - key: DB_PORT
        value: 11323
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        sync: false
      - key: MYSQL_ATTR_SSL_CA
        value: /etc/ssl/certs/ca-certificates.crt

  # Sitio Estático para el Frontend (Expo Web - completamente GRATIS)
  - type: web
    name: stocklimp-frontend
    branch: APP-Android-IOS-Web
    env: static
    rootDir: front
    buildCommand: npm install && npx expo export -p web
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: EXPO_PUBLIC_API_URL
        value: https://stocklimp-backend.onrender.com
